apiVersion: v1
kind: Namespace
metadata:
  name: slink-webhook
---
apiVersion: v1
kind: Service
metadata:
  namespace: slink-webhook
  name: slink-webhook
spec:
  selector:
    app: slink-webhook
  ports:
  - port: 443
    name: https
    targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: slink-webhook
  name: slink-webhook
spec:
  selector:
    matchLabels:
      app: slink-webhook
  template:
    metadata:
      labels:
        app: slink-webhook
    spec:
      enableServiceLinks: false
      containers:
      - name: slink-webhook
        image: docker.io/uablrek/slink-webhook:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_LEVEL
          value: "0"
        - name: CRT_FILE
          value: "/cert/slink-webhook.crt"
        - name: KEY_FILE
          value: "/cert/slink-webhook.key"
        ports:
          - containerPort: 8443
            name: https
        livenessProbe:
          httpGet:
            path: /health
            port: https
            scheme: HTTPS
          failureThreshold: 1
          periodSeconds: 30
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: slink-webhook
  labels:
    app: slink-webhook
webhooks:
  - name: slink-webhook.default.svc
    admissionReviewVersions: ["v1"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ0VENDQXNtZ0F3SUJBZ0lVT28rYlZoUW5hZGtJK2RJVjh2T3VsM3N1UE5Nd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRW9NQ1lHQTFVRUF3d2ZjMnhwYm1zdGQyVmlhRzl2YXk1emJHbHVheTEzWldKb2IyOXJMbk4yWXpBZQpGdzB5TXpFeU1qY3dPRFExTURoYUZ3MHpNekV5TWpRd09EUTFNRGhhTUNveEtEQW1CZ05WQkFNTUgzTnNhVzVyCkxYZGxZbWh2YjJzdWMyeHBibXN0ZDJWaWFHOXZheTV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDV1R1NlJnb3ZKRTk5WXFjd0hyNkxTK01RZkVIdURsY1FXc2ZVK1AydEJKUTVRdkY4OApYczJGbXdwUEJoVld5U3hkSGdmQSt0RnExV2ovYm12NE5hcnh4SXkyZ1dPVXBmTjJDdEU4MzF1bnFxR1RETUVsCk51ZlNPMkxXeUwvN3R5NG9ZbnhNUCtOM2FBSVdFNWI5REJWNG1lQTV4MGVSTDFIUnhKU1dvNHNHaVJMS0lTOFkKZ1lIUWlZMElTYVRaV0pNOHlKSnkzVGtzem91UHVUc1BHRWJ5QVEzN1RReTZCdko4SVEvWnU3a3IvME5sa1V2UApIbnRyVnR0S2ZSNThkd1B2ekpmWm5EbUhVTEQ2OW9UUXVwVEtWZjNBc1FpekI4L1Y3eGtILzU5UXNTWk9UQWZRCjUwTVZSMUNnVzN2dWVCOXFHSGhWNDAyWmdZaVZLaXZ0V3VSRkFnTUJBQUdqZ2Y0d2dmc3dDd1lEVlIwUEJBUUQKQWdYZ01CTUdBMVVkSlFRTU1Bb0dDQ3NHQVFVRkJ3TUJNSUdGQmdOVkhSRUVmakI4Z2cxemJHbHVheTEzWldKbwpiMjlyZ2h0emJHbHVheTEzWldKb2IyOXJMbk5zYVc1ckxYZGxZbWh2YjJ1Q0gzTnNhVzVyTFhkbFltaHZiMnN1CmMyeHBibXN0ZDJWaWFHOXZheTV6ZG1PQ0xYTnNhVzVyTFhkbFltaHZiMnN1YzJ4cGJtc3RkMlZpYUc5dmF5NXoKZG1NdVkyeDFjM1JsY2k1c2IyTmhiREFkQmdOVkhRNEVGZ1FVZHhLNjlqWUZKME95cW1samFNcHZWdFIwUXpBdwpId1lEVlIwakJCZ3dGb0FVZHhLNjlqWUZKME95cW1samFNcHZWdFIwUXpBd0R3WURWUjBUQVFIL0JBVXdBd0VCCi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFDWEZod0NzQ1pja3hhTDRsSlFCaWw3TXBSbGtPVitZYTB4RS8KaG5SMGpzd1NPbE8zSHVYNzJlTjAwb2NkQXBBVGpza1hubGJPclB1eElXQmQ3K3hXR2E5aDhCVEZiM1hRQUpWcApmUnFac1RwSzVUK0hNKzVscjRVOWx1QUp3a1N2dC8veUZRVVMwZm8vMktMdVJXeTJxNnMvMWxaS2Y2a3VBZFJyCmgyNy9pY3FFTXNMd1FGMzJwMUJtb1FDbGhEcUVaYUJrY2wwM2xkZjh6MUV5cCtqN2VkQlZ2UW9qclAwc04rK2kKdEVpR1RtSFQyOG9aclZIV0JlQzBDS2hGbXhCSEdpNUlCd3VRTjd4cTBodFJhYjVIdjd2bmp3NDV2VzkrWHRxcgpFWUJxaFZsMHRQUkJiM3pEeUN3RFJIVlNCOHVFVEVLUmpydklvRzFXb0loR1BLWUVSUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: slink-webhook
        namespace: slink-webhook
        path: "/"
        port: 443
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    timeoutSeconds: 5
    reinvocationPolicy: Never
    failurePolicy: Ignore
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["kube-system", "slink-webhook"]
